package com.example.marketplacepuj.core

const val REALTIME_PRODUCTS_KEY = "productos"
const val REALTIME_CATEGORIES_KEY = "categorias"
const val REALTIME_CATEGORY_NAME_KEY = "nombreCategoria"
const val REALTIME_SUB_CATEGORY_NAME_KEY = "nombreSubCategoria"
const val REALTIME_SUBCATEGORY_KEY = "subcategorias"
const val REALTIME_CATEGORY_STATE_KEY = "estadoCategoria"
const val REALTIME_SUB_CATEGORY_STATE_KEY = "estadoSubCategoria"
const val REALTIME_PRODUCT_STATE_KEY = "activo"
const val REALTIME_PRODUCT_NAME_KEY = "nombre"
const val REALTIME_PRODUCT_DESCRIPTION_KEY = "descripcion"
const val REALTIME_PRODUCT_ID_KEY = "idProducto"
const val REALTIME_USER_ID_KEY = "idUsuario"
const val REALTIME_ORDER_ID_KEY = "idPedido"
const val REALTIME_PRODUCT_PRICE_KEY = "precio"
const val REALTIME_PRODUCT_SUBCATEGORY_KEY = "subcategoria"
const val REALTIME_PRODUCT_SIZE_VALUES_KEY = "tallas"
const val REALTIME_PRODUCT_IMG_KEY = "url_imagen"
const val REALTIME_PRODUCT_QUANTITY_KEY = "cantidadDisponible"
const val REALTIME_PRODUCT_CATEGORY_KEY = "categoria"
const val REALTIME_ORDERS_CATEGORY_KEY = "pedidos"
const val REALTIME_USERS_KEY = "usuarios"
const val REALTIME_ORDER_DETAIL_KEY = "detallePedido"